### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by evgenius1424** [dan5py/turborepo-shadcn-ui#18]
Hi, I'd like to add vite. But I am stuck with some setup issues.

1. cd apps && npx create-vite vite --template react-ts
2. git add . && git commit -m "Add vite"       
3. Add dependency to @repo/ui and tailwind in vite/package.json and do pnpm install
`  "dependencies": {
    "@repo/ui": "workspace:*",`
4. Change button in App.tsx to shadcn/ui button.
`        <Button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </Button>`

pnpm dev leads to this error

Error: The following dependencies are imported but could not be resolved:
@ui/lib/utils (imported by /Users/evgenius1424/fleet/turborepo-shadcn-ui/packages/ui/src/components/ui/button.tsx)

I am pretty sure that we need to add the same logic that we have in next.js.

I see files like postcss.config.js, next.config.js and tailwind.config.ts but no direct path to the vite config configuration.

I've raised a PR, so if you have any ideas just let me know.
https://github.com/dan5py/turborepo-shadcn-ui/pull/19

**Comment by evgenius1424** [comment]
Hi @dan5py, I think you can merge my PR and close this issue. Thanks for your help.

**Comment by evgenius1424** [comment]
Thank you for your help. I'm closing this issue, but will continue to support fork with two applications. For my personal needs.

https://github.com/evgenius1424/turborepo-vite-shadcn-ui

**Comment by dan5py** [comment]
Thank you @evgenius1424 
That's great 💪.
