### ISSUE TITLE
question: path alias in both tsconfig?

### ISSUE THREAD

**Issue by da1z** [dan5py/turborepo-shadcn-ui#20]
I hit an issue where i get runtime errors without this path alias https://github.com/dan5py/turborepo-shadcn-ui/blob/main/packages/typescript-config/nextjs.json#L13 like 
```
web:dev:  ⨯ ../../packages/ui/src/components/ui/button.tsx:4:0
web:dev: Module not found: Can't resolve '@/utils/cn'.
``` 
could you please elaborate why having only this one is not enough https://github.com/dan5py/turborepo-shadcn-ui/blob/main/packages/ui/tsconfig.json#L6 . does it mean if i want to use alias like @/* in both package/ui and apps/docs they will be conflicting and I need separate alias for ui package? 
am I better just go without aliases?

**Comment by dan5py** [comment]
> does it mean if i want to use alias like @/* in both package/ui and apps/docs they will be conflicting and I need separate alias for ui package?

That's right, since the `ui` package is imported inside the app you cannot have the same path alias in both.

Remember that by default the `nextjs` tsconfig has only the `@ui/*` path alias. So if you add the `@/*` alias inside the app you'll to redeclare the `@ui/*` one
