### ISSUE TITLE
ESLint 9 Compatibility Issue

### ISSUE THREAD

**Issue by CodeChooch4** [dan5py/turborepo-shadcn-ui#25]
pnpm lint and turbo lint error with follow error message, it looks like config files changed from EsLint 9.0.0 and up...
![image](https://github.com/dan5py/turborepo-shadcn-ui/assets/131622321/0fbe3f98-df3b-40b4-b672-0f44e0047ebc)

**Comment by dan5py** [comment]
Hey @dugan-dev, thank you for reporting that.
I've just took a better look at the "migrate to 9.x" docs and it does deprecate the `.eslintrc` configuration. (You can see it [here](https://eslint.org/docs/latest/use/migrate-to-9.0.0#-new-default-config-format-eslintconfigjs)).

Completely missed that, I'll fix that ASAP.

**Comment by dan5py** [comment]
Just reverted to eslint 8.
