### ISSUE TITLE
UI that imports other UI in package causes causes error I found a solution

### ISSUE THREAD

**Issue by bernardstein** [dan5py/turborepo-shadcn-ui#28]
so if you use a component like toast or form that imports another ui element it cant find it when building change the @ui/*: [./src/*] to @repo/ui/*: [./src/*]

**Comment by bernardstein** [comment]
also change the import alias to   "aliases": {
    "components": "@repo/ui/components",
    "utils": "@repo/ui/lib/utils"
  }

**Comment by bernardstein** [comment]
that way when adding a component like form or toast it creates the import like import { Label } from "@repo/ui/components/ui/label"; and  import { cn } from "@repo/ui/lib/utils";

**Comment by bernardstein** [comment]
in the ui's package.json my exports are:   "exports": {
    "./components/*": [
      "./src/components/*.ts",
      "./src/components/*.tsx"
    ],
    "./lib/*": "./src/lib/*.ts",
    "./globals.css": "./src/globals.css",
    "./tailwind.config": "./tailwind.config.ts",
    "./postcss.config": "./postcss.config.js"
  }
}

**Comment by fkysly** [comment]
packages/ui/src/components/ui/*:
* replace @ui/components/ui to ../ui
* replace @ui/lib to ../../lib

packages/ui/component.json:
```json
"aliases": {
    "components": "../components",
    "utils": "../../lib/utils"
  }
```

**Comment by dan5py** [comment]
@fkysly that would be good but it doesn't work. The CLI requires valid ts aliases and absolute/relative paths throw an error.

**Comment by dan5py** [comment]
Should work fine now, thanks @bernardstein
