### ISSUE TITLE
Hello sir, i got an issue just like in the picture below, may i ask you why? Thanksss

### ISSUE THREAD

**Issue by Adiyasa26** [dan5py/turborepo-shadcn-ui#3]
![image](https://github.com/dan5py/turborepo-shadcn-ui/assets/51077296/bc5a063c-49dd-4464-b2c5-f2648083fb47)

**Comment by Adiyasa26** [comment]
The error said
`'Button' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
index.d.ts(198, 9): 'children' is declared here.`

**Comment by matheralvs** [comment]
@Adiyasa26 Are you using npm version or pnpm version?

**Comment by dan5py** [comment]
Hi @Adiyasa26, that's usually a bug with the TS server, can you try restarting VSCode and see if the error persists?

**Comment by Adiyasa26** [comment]
> @Adiyasa26 Are you using npm version or pnpm version?

I use pnpm version @matheralvs

**Comment by Adiyasa26** [comment]
> Hi @Adiyasa26, that's usually a bug with the TS server, can you try restarting VSCode and see if the error persists?

Yes i already try restart the ts and restart vscode too @dan5py

**Comment by offlink-io** [comment]
+1 i have the same problem when i'am trying to build my code

**Comment by dan5py** [comment]
Does this problem still occur? @Adiyasa26, @la-ruee-vers-le-bois

**Comment by tmzq** [comment]
Ran into the same issue:
<img width="590" alt="image" src="https://github.com/dan5py/turborepo-shadcn-ui/assets/146925112/6b63afeb-7307-4df9-9d73-097dde7f81fe">

**Comment by dan5py** [comment]
Should be fixed with the latest release `1.1.0`
