### ISSUE TITLE
Can You add a vite app 

### ISSUE THREAD

**Issue by TamjidAhmed10** [dan5py/turborepo-shadcn-ui#32]
I really appretiate your works. But i am a beginer. can you add a vite app with correct information. it would complete this project.

**Comment by evgenius1424** [comment]
Hi @TamjidAhmed10, we have already had [this discussion](https://github.com/dan5py/turborepo-shadcn-ui/pull/19) with @dan5py. I've implemented vite support in my own fork, so you can have a look at it https://github.com/evgenius1424/turborepo-vite-shadcn-ui

**Comment by TamjidAhmed10** [comment]
Thanks bro...🌸🌸
