### ISSUE TITLE
shadcn CLI

### ISSUE THREAD

**Issue by dvzrd** [dan5py/turborepo-shadcn-ui#38]
Hey, great library, it's been really helpful. Thanks for sharing it.

I'm having issues using the ui script inside the ui package to add components. I think it may have something to do with pnpm dlx - I'm used to yarn and npm so perhaps I need to configure pnpm globally for this command to work? Not really sure.

Inside the ui package root dir, I ran this command: `pnpm ui add aspect-ratio`

The gist of the error was: `Command failed with ENOENT: shadcn-ui add aspect-ratio`

If there was some initial setup/config required to get the CLI commands to work with pnpm dlx, it might be a good idea to add that info in the README in case others run into the same issue (seems like a common issue)

I was able to add components just fine using the CLI with the npx command from the docs: `npx shadcn@latest add aspect-ratio`, but I was curious how you got the CLI to work with the pnpm command.

**Comment by dan5py** [comment]
Hi @dvzrd, that scripts shouldn't be using the old `shadcn-ui` CLI but the new `shadcn` CLI.
What version are you on (of this template)?

**Comment by dan5py** [comment]
Closing this for now
