### ISSUE TITLE
routes-manifest.json couldn't be found

### ISSUE THREAD

**Issue by federicofanini** [dan5py/turborepo-shadcn-ui#41]
Hey @dan5py! 

Thanks for sharing this repo. 

I'm trying to deploy it on Vercel but got this error. Are you able to help me?

Ref. https://github.com/vercel/vercel/blob/main/errors/now-next-routes-manifest.md 

`Error: The file "/vercel/path0/apps/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.`

**Comment by dan5py** [comment]
Hey @federicofaninil, I just tried to deploy this repo to Vercel without making any changes and it worked.
Did you set the `Root Directory` during the deployment?

![image](https://github.com/user-attachments/assets/48f5b74f-b0e7-4721-9816-e41054a53d30)

**Comment by dan5py** [comment]
Closing this for now
