### ISSUE TITLE
Use next 15

### ISSUE THREAD

**Issue by hsavit1** [dan5py/turborepo-shadcn-ui#42]
hello,

it would be super helpful if you could implement an upgrade to next 15, now that it's stable. thank you

**Comment by dan5py** [comment]
Hi @hsavit1, although next 15 is marked as stable, I prefer waiting a little bit before updating the template.
Notice that this template isn't made just for Nextjs so you can freely set any version of the framework you want.

## How to update to Next 15

### Update packages
Update `next` and `@next/eslint-plugin-next` to version `15.0.1` (latest)

### Migrate `next.config.mjs` to Typescript
Rename `next.config.mjs` to `next.config.ts`, and add the following content:
```ts
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  transpilePackages: ["@repo/ui"],
};

export default nextConfig;
```

That should be all you need to change in the template.
`shadcn-ui` should be already working with Next 15 but I've seen some people having issues when using React 19 (which you can update if you need to)
