### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by bernardstein** [dan5py/turborepo-shadcn-ui#5]
![Screenshot 2023-07-09 092855](https://github.com/dan5py/turborepo-shadcn-ui/assets/48196828/5bf7fed1-2c30-4512-a145-73a8d6668311)

I am trying to import using "@ui/lib/utils" but instead its making me import using this, both the tsconfig and components files are the same as the original project

**Comment by chris-snow** [comment]
@bernardstein How did you resolve this?
