### ISSUE TITLE
How to implement Dark mode?

### ISSUE THREAD

**Issue by kernelsoe** [dan5py/turborepo-shadcn-ui#7]
Thanks for this template!

Shadcn's dark mode works well inside `apps/` workspace.
But how can we add dark mode inside the `packages/ui`?

Doc says to wrap ThemeProvider in layout.

**Comment by kernelsoe** [comment]
Oh, I was able to add dark mode by wrapping ThemeProvider in respective `apps/` layouts. 😄
Shall I open PR?

**Comment by dan5py** [comment]
Hi @kernelsoe, thanks for wanting to contribute but I think it would be better without ThemeProvider by default. I feel it's best to let anyone install it later if they need to.

**Comment by kernelsoe** [comment]
@dan5py Thanks for the feedback! I'll close this. :)
