### ISSUE TITLE
Use with Expo?

### ISSUE THREAD

**Issue by shawnmclean** [dan5py/turborepo-shadcn-ui#8]
Hi there!

Great work on the template, I'm following it to lay on top of T3.

Any idea if it works with expo?

Pretty new to this so looking out for any blockers that may arise during this migration.

**Comment by dan5py** [comment]
Hi @shawnmclean, this repository uses `shadcn/ui` which is not compatible with React Native. Maybe you can try using other libraries that port `shadcn/ui` to RN.
